import { Content } from './content.model';
import { IContentDocument } from './content.interface';
import { CreateContentDTO, UpdateContentDTO } from './content.types';
import { IPaginationResult } from '../../utils/pagination';
import { AppError } from '../../utils/AppError';
import { Messages } from '../../constants/messages';

export class ContentService {
  /**
   * Create and save a new AI generated content document.
   */
  public static async createContent(data: CreateContentDTO): Promise<IContentDocument> {
    const content = new Content(data);
    return await content.save();
  }

  /**
   * Get a specific content document by its ID, ensuring it belongs to the user.
   */
  public static async getContentById(id: string, userId: string): Promise<IContentDocument> {
    const content = await Content.findOne({ _id: id, userId });
    if (!content) {
      throw new AppError(Messages.CONTENT.NOT_FOUND, 404);
    }
    return content;
  }

  /**
   * Get all content generated by a user, with filters and pagination.
   */
  public static async getAllContent(
    userId: string,
    filters: { type?: string },
    pagination: IPaginationResult
  ): Promise<{ contents: IContentDocument[]; total: number }> {
    const query: Record<string, any> = { userId };
    
    if (filters.type) {
      query.type = filters.type;
    }

    const total = await Content.countDocuments(query);
    const contents = await Content.find(query)
      .sort({ [pagination.sortBy]: pagination.sortOrder })
      .skip(pagination.skip)
      .limit(pagination.limit);

    return { contents, total };
  }

  /**
   * Update a content document.
   */
  public static async updateContent(
    id: string,
    userId: string,
    updateData: UpdateContentDTO
  ): Promise<IContentDocument> {
    const content = await Content.findOneAndUpdate(
      { _id: id, userId },
      updateData,
      { new: true, runValidators: true }
    );

    if (!content) {
      throw new AppError(Messages.CONTENT.NOT_FOUND, 404);
    }
    return content;
  }

  /**
   * Delete a content document.
   */
  public static async deleteContent(id: string, userId: string): Promise<void> {
    const result = await Content.deleteOne({ _id: id, userId });
    if (result.deletedCount === 0) {
      throw new AppError(Messages.CONTENT.NOT_FOUND, 404);
    }
  }
}
export default ContentService;
