import { Content } from './content.model';
import { IContentDocument } from './content.interface';
import { CreateContentDTO, UpdateContentDTO } from './content.types';
import { IPaginationResult } from '../../utils/pagination';
import { AppError } from '../../utils/AppError';
import { Messages } from '../../constants/messages';

export class ContentService {
  /**
   * Create and save a new AI generated content document.
   */
  public static async createContent(data: CreateContentDTO): Promise<IContentDocument> {
    const content = new Content(data);
    return await content.save();
  }

  /**
   * Get a specific content document by its ID, ensuring it belongs to the user (unless ADMIN or MANAGER).
   */
  public static async getContentById(id: string, userId: string, userRole?: string): Promise<IContentDocument> {
    const query: Record<string, any> = { _id: id };
    if (userRole !== 'admin' && userRole !== 'manager') {
      query.userId = userId;
    }
    const content = await Content.findOne(query);
    if (!content) {
      throw new AppError(Messages.CONTENT.NOT_FOUND, 404);
    }
    return content;
  }

  /**
   * Get all content generated by a user or all users (for ADMIN/MANAGER), with filters and pagination.
   */
  public static async getAllContent(
    userId: string,
    userRole: string | undefined,
    filters: { type?: string; search?: string; dateRange?: string; all?: boolean },
    pagination: IPaginationResult
  ): Promise<{ contents: IContentDocument[]; total: number }> {
    const query: Record<string, any> = {};

    // Restrict to current user unless it's a global search (allowed only for ADMIN/MANAGER)
    if (filters.all && (userRole === 'admin' || userRole === 'manager')) {
      // Global search: do not restrict by userId
    } else {
      query.userId = userId;
    }
    
    if (filters.type) {
      query.type = filters.type;
    }

    if (filters.search) {
      query.$or = [
        { prompt: { $regex: filters.search, $options: 'i' } },
        { output: { $regex: filters.search, $options: 'i' } }
      ];
    }

    if (filters.dateRange && filters.dateRange !== 'all') {
      const now = new Date();
      const limitDate = new Date();
      if (filters.dateRange === '24h') {
        limitDate.setHours(now.getHours() - 24);
      } else if (filters.dateRange === '7d') {
        limitDate.setDate(now.getDate() - 7);
      } else if (filters.dateRange === '30d') {
        limitDate.setDate(now.getDate() - 30);
      }
      query.createdAt = { $gte: limitDate };
    }

    const total = await Content.countDocuments(query);
    const contents = await Content.find(query)
      .sort({ [pagination.sortBy]: pagination.sortOrder })
      .skip(pagination.skip)
      .limit(pagination.limit);

    return { contents, total };
  }

  /**
   * Update a content document (ADMIN and MANAGER bypass ownership check).
   */
  public static async updateContent(
    id: string,
    userId: string,
    userRole?: string,
    updateData?: UpdateContentDTO
  ): Promise<IContentDocument> {
    const query: Record<string, any> = { _id: id };
    if (userRole !== 'admin' && userRole !== 'manager') {
      query.userId = userId;
    }

    const content = await Content.findOneAndUpdate(
      query,
      updateData,
      { new: true, runValidators: true }
    );

    if (!content) {
      throw new AppError(Messages.CONTENT.NOT_FOUND, 404);
    }
    return content;
  }

  /**
   * Delete a content document (ADMIN and MANAGER bypass ownership check).
   */
  public static async deleteContent(id: string, userId: string, userRole?: string): Promise<void> {
    const query: Record<string, any> = { _id: id };
    if (userRole !== 'admin' && userRole !== 'manager') {
      query.userId = userId;
    }

    const result = await Content.deleteOne(query);
    if (result.deletedCount === 0) {
      throw new AppError(Messages.CONTENT.NOT_FOUND, 404);
    }
  }
}
export default ContentService;
